

testwriter: testwriter.c 
	gcc -o testwriter testwriter.c -I"/home/ubuntu/msherman_nsfrb/DSA110-NSFRB-PROJECT/dsa110-nsfrb/realtime/rtwriter/" -lrtwriter -L"/home/ubuntu/msherman_nsfrb/DSA110-NSFRB-PROJECT/dsa110-nsfrb/realtime/rtwriter/"


