#!/bin/bash

#main
#dada_db -k cada -d
#dada_db -k caea -d
#dada_db -k cafa -d
#slow
#dada_db -k cadb -d
#dada_db -k caeb -d
#dada_db -k cafb -d
#imgdiff
#dada_db -k cadc -d
#dada_db -k caec -d
#dada_db -k cafc -d
#dada_db -k cbba -d
#dada_db -k cbba -d
#dada_db -k cbbd -d
#dada_db -k cbbe -d
#dada_db -k cbbf -d
#dada_db -k cbca -d
#dada_db -k cbcb -d
#dada_db -k cbcc -d
#dada_db -k cbcd -d
#dada_db -k cbce -d
#dada_db -k cbcf -d
#dada_db -k cbda -d
#dada_db -k cbdb -d
#dada_db -k cbdc -d
#dada_db -k cbde -d        
#dada_db -k cbbb -d
#dada_db -k cbbc -d
#dada_db -k cbbd -d
dada_db -k cbba -d
kill -9 -"$(pgrep run_proc_server_search)"

