#!/bin/bash
rt="true" #"true"
completeness="false"
multiports=$(seq 8810 8825) 
cpunums="38-39" #"23-39"
cpunums2="5-19"
echo $multiports
> $PWD/process_log.txt #/home/ubuntu/proj/dsa110-shell/dsa110-nsfrb/process_server/process_log.txt 
if [ "$rt" = "true" ]; 
then
	echo "realtime process server active"
	#dada_db -k cbba -b 98000064 -n 2 -a 4096
	#dada_db -k cbba -b 6125064 -n 2 -a 4096
	#dada_db -k cbbd -b 6125064 -n 2 -a 4096
	#dada_db -k cbbe -b 6125064 -n 2 -a 4096
	#dada_db -k cbbf -b 6125064 -n 2 -a 4096
	#dada_db -k cbca -b 6125064 -n 2 -a 4096
	#dada_db -k cbcb -b 6125064 -n 2 -a 4096
	#dada_db -k cbcc -b 6125064 -n 2 -a 4096
	#dada_db -k cbcd -b 6125064 -n 2 -a 4096
	#dada_db -k cbce -b 6125064 -n 2 -a 4096
	#dada_db -k cbcf -b 6125064 -n 2 -a 4096
	#dada_db -k cbda -b 6125064 -n 2 -a 4096
	#dada_db -k cbdb -b 6125064 -n 2 -a 4096
	#dada_db -k cbdc -b 6125064 -n 2 -a 4096
	#dada_db -k cbde -b 6125064 -n 2 -a 4096
	#dada_db -k cbbb -b 6125064 -n 2 -a 4096
	#dada_db -k cbbc -b 6125064 -n 2 -a 4096
	#dada_db -k cbbd -b 6125064 -n 2 -a 4096
	#taskset --cpu-list $cpunums python run_RX.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --etcd --SNRthresh 8.5 --noiseth 3 --nsamps 25 --gridsize 175 --port 8080 --multiport $multiports --realtime --slow --imgdiff --forfeit --rtastrocal --maxProcesses 20 --protocol tcp --initframes --rtastrocalrange 92 --rejectnoiseoutliers --timeout_SELECT 0.005 --timeout_SOCKET 0.05 --timeout_INLOOP 0.055 --timeout_LOOP 0.05 --psrdadakey cbba --timeout_SLEEP 0.01 --timeout_FAILSAFE 5 --BADITERS 100 --timeout_BADCOUNTER 30
	#dada_db -k cbbd -b 6125064 -n 2 -a 4096
        #taskset --cpu-list $cpunums python run_RX.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --etcd --SNRthresh 8.5 --noiseth 3 --nsamps 25 --gridsize 175 --port 8080 --multiport $multiports --realtime --slow --imgdiff --forfeit --rtastrocal --maxProcesses 20 --protocol tcp --initframes --rtastrocalrange 92 --rejectnoiseoutliers --timeout_SELECT 0.005 --timeout_SOCKET 0.07 --timeout_INLOOP 0.07 --timeout_LOOP 0.05 --psrdadakey cbba --timeout_SLEEP 0.01 --timeout_FAILSAFE 5 --BADITERS 100 --timeout_BADCOUNTER 30
	taskset --cpu-list $cpunums python run_RX.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --etcd --SNRthresh 8.5 --noiseth 3 --nsamps 25 --gridsize 175 --port 8080 --multiport $multiports --realtime --slow --imgdiff --forfeit --rtastrocal --maxProcesses 20 --protocol tcp --initframes --rtastrocalrange 92 --rejectnoiseoutliers --timeout_SELECT 0.1 --timeout_SOCKET 0.061 --timeout_INLOOP 0.06 --timeout_LOOP 0.06 --psrdadakey cbba --timeout_SLEEP 0.01 --timeout_FAILSAFE 5 --BADITERS 1 --timeout_BADCOUNTER 30 --timeout_RESTART 30
else
	echo "offline process server active"
	if [ "$completeness" = "true" ];
	then
		echo "--completeness test"
		cp -r $NSFRBDIR-noise $NSFRBDIR-noise-backup 
		cp -r $NSFRBDIR-frames $NSFRBDIR-frames-backup
		#on exit, restore
		trap 'rm -r $NSFRBDIR-noise; mv $NSFRBDIR-noise-backup $NSFRBDIR-noise; rm -r $NSFRBDIR-frames; mv $NSFRBDIR-frames-backup $NSFRBDIR-frames' EXIT
		
		taskset --cpu-list $cpunums python run.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --etcd --SNRthresh 6 --noiseth 3 --nsamps 25 --gridsize 301 --port 8080 --multiport 8810 8811 8812 8813 8814 8815 8816 8817 8818 8819 8820 8821 8822 8823 8824 8825 --completeness "$@" #--initnoise --initnoisezero
	else
		taskset --cpu-list $cpunums python run.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --etcd --SNRthresh 5 --noiseth 3 --nsamps 25 --gridsize 301 --port 8080 --multiport 8810 8811 8812 8813 8814 8815 8816 8817 8818 8819 8820 8821 8822 8823 8824 8825 --slow --imgdiff --forfeit "$@" --initnoise --initnoisezero --testsinglenode
	fi
fi
