#!/bin/bash
rt="true" #"true"
completeness="false"
multiports=$(seq 8810 8825) 
cpunums="23-39"
echo $multiports
> $PWD/process_log.txt #/home/ubuntu/proj/dsa110-shell/dsa110-nsfrb/process_server/process_log.txt 
if [ "$rt" = "true" ]; 
then
	echo "realtime process server active"
	taskset --cpu-list $cpunums python run.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --etcd --SNRthresh 4 --noiseth 3 --nsamps 25 --gridsize 175 --port 8080 --multiport $multiports --realtime --slow --imgdiff --forfeit --rtastrocal --maxProcesses 80 --protocol tcp --initframes #--lockdev 1 #--savesearch
else
	echo "offline process server active"
	if [ "$completeness" = "true" ];
	then
		echo "--completeness test"
		cp -r $NSFRBDIR-noise $NSFRBDIR-noise-backup 
		cp -r $NSFRBDIR-frames $NSFRBDIR-frames-backup
		#on exit, restore
		trap 'rm -r $NSFRBDIR-noise; mv $NSFRBDIR-noise-backup $NSFRBDIR-noise; rm -r $NSFRBDIR-frames; mv $NSFRBDIR-frames-backup $NSFRBDIR-frames' EXIT
		
		taskset --cpu-list $cpunums python run.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --etcd --SNRthresh 6 --noiseth 3 --nsamps 25 --gridsize 301 --port 8080 --multiport 8810 8811 8812 8813 8814 8815 8816 8817 8818 8819 8820 8821 8822 8823 8824 8825 --completeness "$@" #--initnoise --initnoisezero
	else
		taskset --cpu-list $cpunums python run.py --imgdiffgulps 30 --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --etcd --SNRthresh 5 --noiseth 3 --nsamps 25 --gridsize 301 --port 8080 --multiport 8810 8811 8812 8813 8814 8815 8816 8817 8818 8819 8820 8821 8822 8823 8824 8825 --slow --imgdiff --forfeit "$@" --initnoise --initnoisezero --testsinglenode
	fi
fi
