#!/bin/bash

#run this script to open server, attach to a dask worker, and receive 32x32x25x16 image data
dask worker tcp://127.0.0.1:$DASKPORT --nworkers 1 --nthreads 10 --name process_server_WRKR > $PWD/.process_server_WRKR_log.txt 2>&1 &
> $PWD/process_log.txt #/home/ubuntu/proj/dsa110-shell/dsa110-nsfrb/process_server/process_log.txt 
python run.py --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --savesearch --etcd --initnoise --SNRthresh 20 "$@" 
#python run.py --spacefilter --usefft --samenoise --cuda --appendframe --usejax --offline -T --savesearch --etcd --SNRthresh 20 "$@"
