#!/bin/bash
echo "realtime candcutter active"
python T4_manager.py --subimgpix 301 --SNRthresh 6 --useTOA --psfpercentile 70 --maxcands 10  --cluster --avgcluster --psfcluster --classify3D --clusteriters 2 --maxcand --model_weights3D "/dataz/dsa110/nsfrb/dsa110-nsfrb-training/NN_train/enhanced3dcnn_weights_final3.pth" --classcut --toslack "$@" #--cluster --psfcluster --classify3D
