#!/bin/bash
#dask worker tcp://127.0.0.1:$DASKPORT --nworkers 1 --nthreads 10 --name rt_imager_WRKR > $PWD/.rt_imager_WRKR_log.txt 2>&1 &
#> $PWD/realtime_imager_log.txt

#create psrdada buffer
dada_db -k caba -b 14899200

python /home/ubuntu/msherman_nsfrb/DSA110-NSFRB-PROJECT/dsa110-nsfrb/offline/offline_imager_prt.py --num_time_samples 25 --nchans_per_node 8 --gridsize 301 --briggs --robust -2 --verbose --maxProcesses 8 --inject --inject_interval 45 --inject_delay 15 #--search "$@"
