#!/bin/bash
#dask worker tcp://127.0.0.1:$DASKPORT --nworkers 1 --nthreads 10 --name rt_imager_WRKR > $PWD/.rt_imager_WRKR_log.txt 2>&1 &
> $PWD/realtime_imager_log.txt

#create psrdada buffer
dada_db -k caba -b 14899200

python /home/ubuntu/msherman_nsfrb/DSA110-NSFRB-PROJECT/dsa110-nsfrb/realtime/realtime_imager.py 1 --verbose --num_time_samples 25 --nchans_per_node 8 --gridsize 301 --flagBPASS --flagBPASSBURST --briggs --robust 2 --verbose --multiimage "$@"
