#!/bin/bash


#starting RX server
cd /home/ubuntu/proj/dsa110-shell/dsa110-nsfrb/src
./run_server -p >> server_log.txt 2>&1 & 

#starting proc server
cd /home/ubuntu/proj/dsa110-shell/dsa110-nsfrb/process_server
./run_proc_server -T --subimgpix 25 --verbose --SNRthresh 8000 >> process_log.txt 2>&1 &
