name: CI

on:
  push:
    branches:
      - nikita_dev
  pull_request:
    branches:
      - nikita_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install .

    - name: Run Imaging Tests
      working-directory: ./tests
      run: pytest test_imaging.py

    - name: Run Classifying Tests
      working-directory: ./tests
      run: pytest test_classifying.py


